name: Surge PR Preview

on:
  pull_request:
    branches: [ master ]

jobs:
  docs-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        id: docs_preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: docs
          build: |
            npm install
            npm run gen
      - name: Get the preview_url
        run: echo "url => ${{ steps.docs_preview_step.outputs.preview_url }}"

   client-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        id: client_preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: client-dist
          build: |
            npm install
            npm run build:client
      - name: Get the preview_url
        run: echo "url => ${{ steps.client_preview_step.outputs.preview_url }}"
